version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: dimo-dev-console
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/scripts/db:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

volumes:
  db-data: {}
